//
// Created by xtx on 2023/9/17.
//

#ifndef WIRELESSMONITOR_API_COMRECEIVERTHREAD_COMRECEIVERTHREAD_H_
#define WIRELESSMONITOR_API_COMRECEIVERTHREAD_COMRECEIVERTHREAD_H_

class ComReceiverThread {

};

#endif //WIRELESSMONITOR_API_COMRECEIVERTHREAD_COMRECEIVERTHREAD_H_
